---
- name: Create the OpenShift GitOps Application for Global Hub
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/oc apply --kubeconfig {{ target_kubeconfig }} -f -"
    stdin: "{{ lookup('template', 'global-hub-argocd-app.yaml.j2') }}"
  changed_when: true
