---
- name: Install base OCP prerequisites
  ansible.builtin.include_role:
    name: ocp/install_ocp_prerequisites

- name: Download oc-mirror plugin
  import_tasks: download-oc-mirror.yaml

- name: Download mirror-registry installer
  import_tasks: download-mirror-registry.yaml

- name: Download opm (Operator Package Manager)
  import_tasks: download-opm.yaml
