---
- name: Ensure requisite Python modules are installed
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
    state: present
  become: true
  loop:
    - setuptools
    - kubernetes
    - openshift
    - boto3
...