---
gitea_namespace: "gitea"
gitea_source_image: "docker.io/gitea/gitea:1.22-rootless"
gitea_image: "{{ mirror_registry_url }}/{{ mirror_base_path | default('ocp4') }}/gitea/gitea:1.22-rootless"
mirror_registry_dir: "{{ working_dir }}/mirror-registry"
mirror_registry_init_user: "{{ disconnected.mirror_registry.init_user | default('init') }}"
mirror_registry_init_password: "{{ disconnected.mirror_registry.init_password }}"
gitea_admin_user: "gitea-admin"
gitea_admin_password: "{{ disconnected.gitea.admin_password | default('R3dH4t!gitea') }}"
gitea_admin_email: "gitea-admin@local.cluster"
gitea_org: "ocp"
gitea_pvc_size: "10Gi"
gitops_repos_dir: "{{ working_dir }}/gitops-repos"
