---
- name: Create the OpenShift GitOps Application for COO
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/oc apply --kubeconfig {{ target_kubeconfig }} -f -"
    stdin: "{{ lookup('template', 'coo-argocd-app.yaml.j2') }}"
  changed_when: true
