---
- name: Deploy Managed Hub Violations Check Policy
  ansible.builtin.shell:
    cmd: "{{ bin_dir }}/oc apply --kubeconfig {{ target_kubeconfig }} -f -"
    stdin: "{{ lookup('template', 'violations-policy.yaml.j2') }}"
  changed_when: true
